"""add relationships

Revision ID: 7e0ba74606b6
Revises: c730205b1942
Create Date: 2023-10-20 05:32:29.655144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0ba74606b6'
down_revision = 'c730205b1942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISH'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('instructor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'])
    op.add_column('modules', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'course_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'instructor_id')
    op.drop_column('courses', 'category_id')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
