"""edit modules property

Revision ID: d6f5f942a4b2
Revises: 7e0ba74606b6
Create Date: 2023-10-22 06:09:16.667891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f5f942a4b2'
down_revision = '7e0ba74606b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'modules', ['title'], unique=False)
    # ### end Alembic commands ###
